### ISSUE TITLE
Show Definition schema in UI

### ISSUE THREAD

**Issue by hongchaodeng** [oam-dev/velacp#100]
Similar to https://kubevela.io/docs/developers/references/component-types/webservice, we could show the definition schema to users in pretty forms.

An idea would be that when clicking the definition a drawer would show up with the definition forms:

<img width="1234" alt="WechatIMG52" src="https://user-images.githubusercontent.com/920884/118130093-f9c2f000-b3ca-11eb-93dd-7d0bbf5debea.png">

After discussion with @zzxwill , the backend could return the data:
- description
- properties: Two level array type. Top level is the struct name, second level is the tuple (name, description, type, required, default).

**Comment by Ghostbaby** [comment]
@hongchaodeng pls assigned to me

**Comment by Ghostbaby** [comment]
@hongchaodeng @zzxwill

**Comment by zzxwill** [comment]
@Ghostbaby The data seems perfect. Please go ahead make a PR:)
