### ISSUE TITLE
导入集群时出现 405 报错

### ISSUE THREAD

**Issue by chenggui53** [oam-dev/velacp#112]
![image](https://user-images.githubusercontent.com/5997374/120165878-96d8b200-c22e-11eb-9f29-79c0fafcf8ad.png)

**Comment by chenggui53** [comment]
@sunny0826 请问相关的 Kubeconfig 配置有什么规范吗？没有找到相关的说明，我直接使用的 kubectl 的 .kube/config 配置貌似无法导入。

**Comment by lxd5866** [comment]
The function is still being improved, this part of the function may not be available for the time being, please be patient

**Comment by hongchaodeng** [comment]
@chenggui53 你好，非常感谢你提出的 issue。

请问下能给出重现步骤和配置环境吗？这个我们之前开发的时候测试是 OK 的。如果我们能重现一下有助于我们找出源头，并修复 Bug。非常感谢！

**Comment by wangyuan249** [comment]
@chenggui53  您好 我试了一下 提交任意字符的 kubeconfig 目前是可以的。您在图中显示的报错应该是找不到对应请求方法  可以检查一下是否有修改 rest_server.go 中的post方法 url。  或者直接 git pull 下来最新的master分支 再次尝试添加新的cluster

**Comment by Ghostbaby** [comment]
@chenggui53 您好，麻烦使用main分支最新代码试一下，目前看 cluster 的创建是没问题的，issue我先关闭了，有问题可以重新打开。
