### ISSUE TITLE
When will velacp release the version

### ISSUE THREAD

**Issue by wandongwd** [oam-dev/velacp#72]
when will velacp release the version?
I did not find restapi

**Comment by hongchaodeng** [comment]
Hi @wandongwd . Thanks for your interest.
Currently I'm the major developer behind velacp. But I'm more focused on other Vela issues (e.g. https://github.com/oam-dev/kubevela/issues/1144) right now. I expect to spend more time on velacp in early April and finish the rest of the initial work before first release.

The rest API are generated from proto files: https://github.com/oam-dev/velacp/tree/main/pkg/proto

**Comment by hongchaodeng** [comment]
Note that some of the control plane work will be done in KubeVela repo (https://github.com/oam-dev/kubevela/issues/1086). This repo is more about user-facing tools (UI, CLI, APIServer)

**Comment by hongchaodeng** [comment]
Closing this. We will have a release soon in June.
