### ISSUE TITLE
[Brainstorm] Application Page

### ISSUE THREAD

**Issue by hongchaodeng** [oam-dev/velacp#84]
Now the application CRUD is finished, we need to show an application page when user clicks an app:

<img width="1016" alt="WX20210418-233621@2x" src="https://user-images.githubusercontent.com/920884/115178355-1b1c0f00-a09f-11eb-9d52-87b7bb5886d5.png">

This is related to the "application operation" section in https://github.com/oam-dev/kubevela/issues/1495 . A few points I can think of to show in application page:

- metadata
- health
- replica
- logs menu
- metrics menu

Any idea is welcome! Please share your thoughts and ideas on what to show up in the application page.

**Comment by sunny0826** [comment]
I think the following features are also required to be shown:
- exec
- port-forward
- ComponentDefinition(CUE Helm Raw Template)

**Comment by hongchaodeng** [comment]
Another feedback that we got: "It's very important to show app health and provide insights about what went wrong, e.g. process exit 1, oom kill, infra problem (resource insufficient)"
