### ISSUE TITLE
[Backend] Add Cluster Services

### ISSUE THREAD

**Issue by hongchaodeng** [oam-dev/velacp#88]
The frontend makes the following request w.r.t. the cluster services:

```js
export async function listClusterNames() {
  return request<{ clusters: string[] }>('/api/clusternames');
}

export async function listClusters() {
  return request<{ clusters: API.ClusterType[] }>('/api/clusters');
}

export async function addCluster(params: API.ClusterType) {
  return request<{ cluster: API.ClusterType }>('/api/clusters', {
    method: 'POST',
    data: {
      ...params,
      method: 'post',
    },
  });
}

export async function updateCluster(params: API.ClusterType) {
  return request<{ cluster: API.ClusterType }>('/api/clusters', {
    method: 'POST',
    data: {
      ...params,
      method: 'update',
    },
  });
}

export async function removeCluster(params: API.ClusterType) {
  return request<{ cluster: API.ClusterType }>('/api/clusters', {
    method: 'POST',
    data: {
      ...params,
      method: 'delete',
    },
  });
}
```

Type definitions:
```js
  export type ClusterType = {
    name: string;
    desc?: string;
    updatedAt?: number; // unix milliseconds
    kubeconfig?: string;
  };

```

We need to implement these services in backend.

**Comment by mosesyou** [comment]
assign to me plz :)

**Comment by hongchaodeng** [comment]
@mosesyou 
Note that listComponentDefinitions and listTraitDefinitions are a bit more complicated.
You might need to get kube client first -- use [this code](https://github.com/oam-dev/kubevela/blob/675b0e24db0cedde11c9870242763957b0012f99/pkg/clustermanager/cluster_manager.go#L27). And then list those definitions from k8s clusters.

**Comment by hongchaodeng** [comment]
@mosesyou 
I have moved out listXXXDefinitions into https://github.com/oam-dev/velacp/issues/96 as a separate task so that you don't need to implement it in https://github.com/oam-dev/velacp/pull/94

**Comment by mosesyou** [comment]
> @mosesyou
> I have moved out listXXXDefinitions into #96 as a separate task so that you don't need to implement it in #94

ok
