### ISSUE TITLE
[Backend] Add service to install kubevela controller into cluster

### ISSUE THREAD

**Issue by hongchaodeng** [oam-dev/velacp#91]
The frontend makes the following request to install kubevela controller:

```js
export async function installVelaController(cluster: string, helmrepo: string, version: string) {
  return request<{version: string}>( // returns the version that's been installed
    `/api/clusters/${cluster}/installvela`
  )
}
```

We need to implement these services in backend.

**Comment by qingfengming** [comment]
@hongchaodeng pls assigned to me

**Comment by hongchaodeng** [comment]
Reassigning to @yangsoon since no update for more than a week and he is also interested.
仍然非常感谢您对开源的支持和兴趣~ @qingfengming

**Comment by qingfengming** [comment]
不好意思，之前看到依赖cluster接口，写的慢了些。快写完了才看到指给别人了，还是提一下吧，说不定可以参考一下。

**Comment by hongchaodeng** [comment]
@qingfengming 没事~ @yangsoon 还没开始弄。既然你已经写完 PR 了，那我们就先合并吧。非常感谢您！

**Comment by hongchaodeng** [comment]
https://github.com/oam-dev/velacp/pull/98 is merged.
Also need to update the UI cluster page to call the service @yangsoon
