### ISSUE TITLE
Implement isVelaInstalled and fix installVelaController

### ISSUE THREAD

**Issue by hongchaodeng** [oam-dev/velacp#99]
Currently, the UI page relies on the isVealInstalled API to check vela controller status:

https://github.com/oam-dev/velacp/blob/d80a1c7d4d721e61d26acd0d49574b913fced7b1/ui/src/services/kubevela/clusterapi.ts#L55

The backend service needs to be implemented.

------

Additionally, the current UI code didn't set the helm repo and version:

https://github.com/oam-dev/velacp/blob/d80a1c7d4d721e61d26acd0d49574b913fced7b1/ui/src/pages/Cluster/Detail/index.tsx#L40

Needs to fix this and ensure it work.

The actual UI looks like:

<img width="608" alt="WX20210512-222743@2x" src="https://user-images.githubusercontent.com/920884/118068970-4b3e9100-b371-11eb-8fc2-493a83317a63.png">

**Comment by qingfengming** [comment]
please assign to me

**Comment by hongchaodeng** [comment]
Hi @qingfengming . Sorry but @baxiaoshi already pinged me in Dingding yesterday and sign up for this issue. Will notify you next time when we have new issues :)

Could you add me in Dingding too? I will ping you next time too.

**Comment by qingfengming** [comment]
> Hi @qingfengming . Sorry but @baxiaoshi already pinged me in Dingding yesterday and sign up for this issue. Will notify you next time when we have new issues :)
> 
> Could you add me in Dingding too? I will ping you next time too.

ok
